### ISSUE TITLE
Leaked AWS Credentials Your app(s) expose Amazon Web Services credentials.

### ISSUE THREAD

**Issue by iAbdul** [aws-amplify/amplify-ui-android#116]
Hi,

I have integrated liveness component in my droid application & used customcredentialprovider using accesskey & secret key. when i uploaded app to play store, i received error from them "Leaked AWS Credentials
Your app(s) expose Amazon Web Services credentials." . can you help me, how to fix this?

Thanks!

**Comment by phantumcode** [comment]
Transferring this issue to the Amplify Android repo.  Please provide best practices for storing credentials in Android app.

**Comment by tylerjroach** [comment]
Thank you for contacting us regarding the “Leaked AWS Credentials. Your app(s) expose Amazon Web Services credentials.” warning you received. We strongly recommend that AWS Access Keys and Secret Keys not be embedded into a client application. Please see this [page](https://aws.amazon.com/blogs/security/what-to-do-if-you-inadvertently-expose-an-aws-access-key/) for details on this issue and instructions for revoking the current embedded Access Key and Secret Key.

For best practices on securing your Access Keys and Secret Keys, please see [Managing access keys for IAM users](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#securing_access-keys).

> Use temporary security credentials (IAM roles) instead of long-term access keys

> You have a mobile app. Don’t embed access keys with the app, even in encrypted storage. Instead, use [Amazon Cognito](https://aws.amazon.com/cognito/) to manage user identities in your app. This service lets you authenticate users using Login with Amazon, Facebook, Google, or any OpenID Connect (OIDC)–compatible identity provider. You can then use the Amazon Cognito credentials provider to manage credentials that your app uses to make requests to AWS.

Our recommended approach is to use the Amplify Auth category to vend AWS Temporary Credentials. If you are unable to use Amplify, you must fetch AWS Temporary Credentials from your chosen API service.
