### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by emmanuelHa** [aws-amplify/amplify-ui-android#134]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).

### Which UI component is this feature-request for?

Authenticator

### Please include any relevant guides or documentation you're referencing

https://ui.docs.amplify.aws/android/connected-components/authenticator/configuration

### Please describe your feature-request in detail.

In the parent page (https://ui.docs.amplify.aws/android/connected-components/authenticator), it is written to add the following snipet:
`class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    setContent {
      Authenticator { state ->
          SignedInContent(state)
      }
    }
  
SignedInContent ? This code does not compile.
When this feature is done with javascript the ui component woks out of the box.
I am expecting from such a common feature as Signin/Signup workflow a simple code to copy/paste.

### Code Snippet

```java
// Put your code below this line.

```

**Comment by mattcreaser** [comment]
Hi @emmanuelHa - can you elaborate on the compilation error you're seeing?

`SignedInContent` is just a placeholder for your own composable, it should be whatever content you want to show for a signed-in user.

**Comment by emmanuelHa** [comment]
Yes now I know that SignedInContent is "just" a placeholder. But for newcomers that's not what they want. They want something that allow a use case to work from end to end, copy paste a bit of code, test it and then they adapt this code. That' a a simple rule for coding: always quickly loop through code and test. By the way this code does not compile simply because this SignedInContent does not exist.
I propose to add a basic implementation (**for android use case**) with coroutines:
`    
import androidx.compose.runtime.Composable
import com.amplifyframework.ui.authenticator.SignedInState
import androidx.compose.foundation.layout.Column
import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.runtime.rememberCoroutineScope

...

@Composable
    fun SignedInContent(state: SignedInState) {
        val scope = rememberCoroutineScope()
        Column {
            Text("You've signed in as ${state.user.username}!")
            Button(onClick = { scope.launch { state.signOut() } }) {
                Text("Sign Out")
            }
        }
    }
`
Is that ok for you ?

**Comment by mattcreaser** [comment]
Thanks for the suggestion @emmanuelHa. I'll update the documentation accordingly.
