### ISSUE TITLE
compileSdk 31 support

### ISSUE THREAD

**Issue by anahiforesi** [aws-amplify/amplify-ui-android#135]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).

### Which UI component is this feature-request for?

Liveness

### Please describe your feature-request in detail.

Hi, 
I'm trying to implement Amplify Liveness on a project using compileSdk 31 and got several errors because of dependencies needing compileSdk 33 or higher. 
Is there any version that would work on compileSdk 31?
Thanks

**Comment by tylerjroach** [comment]
@anahiforesi Is there something blocking from compiling against 33? You can still use a lower target if necessary.

**Comment by mattcreaser** [comment]
The compileSdk requirement is coming from the Jetpack libraries we use, so we won't be downgrading that requirement. It will probably change to 34 soon, as this the requirement for the latest JetPack libraries. I would suggest having the client applications increase their compile SDK.

Closing this issue, please open a new one if needed.
