### ISSUE TITLE
Authenticator state doesn't update to reflect session state

### ISSUE THREAD

**Issue by arctop-sk** [aws-amplify/amplify-ui-android#139]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Android

### Which UI component?

Authenticator

### How is your app built?

Gradle / Android Studio

### Please describe your bug.

Authenticator UI isn't updated in app after a call to sign out of Amplify.Auth happens.

`val amplifyResult = Amplify.Auth.signOut()`

Call is made outside the scope of the composable Authenticator(){} block.
The Authenticator will still present the SignedInState {} content, even though the user session has been terminated.

Currently, calling the SignedInState.signOut() inside the composable will cause the UI to update

### What's the expected behaviour?

The Authenticator's UI state should reflect the Amplify.Auth state and not require function calls internally to change the state of the UI.

### Help us reproduce the bug!

Use Authenticator UI on android.
Call Amplify.Auth.signOut() from anywhere in the app.
Authenticator UI will still display signedInState

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by mattcreaser** [comment]
Thanks for the report @arctop-sk. This should be working, Authenticator hooks into Amplify Hub events to detect sign out. Someone from our team will take a look.

**Comment by arctop-sk** [comment]
Thanks. 
I'm also noticing some other issues where fetchAuthSession() returns false on signedIn, even though the user has just signed in.

**Comment by mattcreaser** [comment]
Hey @arctop-sk - was this issue resolved with the same change as for [this signedIn=false issue](https://github.com/aws-amplify/amplify-android/issues/2773)?

**Comment by arctop-sk** [comment]
Yes it has. Thank you.
