### ISSUE TITLE
non-COMPOSE Face Liveness  aar

### ISSUE THREAD

**Issue by helloJude** [aws-amplify/amplify-ui-android#165]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).

### Which UI component is this feature-request for?

Authenticator

### Please include any relevant guides or documentation you're referencing

https://ui.docs.amplify.aws/android/connected-components/liveness

### Please describe your feature-request in detail.

my project AGP is  "com.android.tools.build:gradle:4.0.2" , kotlin  is 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21
when i import Face Liveness dependencies ,project compile error. But AGP and kotlin cannot be upgraded due to historical reasons.
Whether there is a non-COMPOSE Face Liveness  aar and docs?

### Code Snippet

```java
// Put your code below this line.

```

**Comment by mattcreaser** [comment]
Hi @helloJude. The Liveness UI component is written in Compose so you would need to be able to upgrade to a more recent build setup to use that, there is no other version. We currently require a Kotlin version of 1.8+ and AGP of 7.4+.

Please let us know if you have any other questions.
