### ISSUE TITLE
❗❗Liveness: Camera preview not centered on screen (Fixed in version 1.0.2)

### ISSUE THREAD

**Issue by tylerjroach** [aws-amplify/amplify-ui-android#52]
### Which UI component?

Liveness

### Describe the bug

Upgrading Material3 UI (androidx.compose.material3:material3) from 1.0.1 to version 1.1.0, caused an issue where the camera preview was top aligned to the screen during the liveness challenge, instead of center aligned. This results in the camera preview not aligning to the face oval.

Impacted Amplify UI Liveness Versions:
* 1.0.0 (Only if the customer upgraded the `androidx.compose.material3:material3` dependency to 1.1.0+) 
* 1.0.1

As a workaround for these versions, you can force downgrade the material3 lib by adding the snippet below to the app build.gradle.

```
configurations.all {
    resolutionStrategy {
        force('androidx.compose.material3:material3:1.0.1')
    }
}
```

Amplify UI Liveness 1.0.2 includes a fix to ensure the camera is properly centered on the screen, and is able to render correctly with `'androidx.compose.material3:material3:1.1.0'` or later.

**Comment by tjleing** [comment]
Closing, notification has been given.
