### ISSUE TITLE
[Authenticator] Incompatible with Compose Animation 1.5.0+

### ISSUE THREAD

**Issue by mattcreaser** [aws-amplify/amplify-ui-android#79]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#reporting-bugsfeature-requests).

### Which UI component?

Authenticator

### Gradle script dependencies

```groovy
// Put output below this line

```

### Environment information

```
# Put output below this line


```

### Please include any relevant guides or documentation you're referencing

https://developer.android.com/jetpack/androidx/releases/compose-animation#1.5.0-alpha01

### Describe the bug

In Compose Animation 1.5.0 the `AnimatedContent` API was made stable, but with the following change:

> AnimatedContent APIs are now stable AnimatedContentScope has been renamed to AnimatedContentTransitionScope. scaleIn and scaleOut are now stable APIs.

### Reproduction steps (if applicable)

1. Try to use Authenticator with Compose Animation 1.5.0+ (this can be pulled in by many other dependencies)
Expected: Authenticator works as normal
Actual: App crashes (see stacktrace below)

### Code Snippet

```java
// Put your code below this line.

```

### Log output

```
2023-09-27 21:46:41.776  4562-4562  AndroidRuntime          com.example.amplicart                E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.amplicart, PID: 4562
                                                                                                    java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~dfs3QkghRFl2MA0JMu0MYw==/com.example.amplicart-ZFt2SGfy_YXZS4CGXfoGpQ==/base.apk)
                                                                                                    	at com.amplifyframework.ui.authenticator.ui.AuthenticatorKt.Authenticator(Authenticator.kt:112)
                                                                                                    	at com.example.amplicart.ComposableSingletons$MainActivityKt$lambda-3$1.invoke(MainActivity.kt:93)
                                                                                                    	at com.example.amplicart.ComposableSingletons$MainActivityKt$lambda-3$1.invoke(MainActivity.kt:92)
```

**Comment by tylerjroach** [comment]
Fixed in 1.0.2 release
