### ISSUE TITLE
Unclear error, when config is misconfigured

### ISSUE THREAD

**Issue by WildOrangutan** [aws-amplify/amplify-ui-android#98]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

When your config is not configured correctly, only `MissingConfigurationException` is thrown. It provides no value, what is wrong and how to fix it.

I presume the issue is on this class: [AuthProvider](https://github.com/aws-amplify/amplify-ui-android/blob/5f0130544182896e734a29d83f08459a23295db7/authenticator/src/main/java/com/amplifyframework/ui/authenticator/util/AuthProvider.kt#L302).

If any error occurs, the exception is swallowed and not reported anywhere.

### Initialization steps (if applicable)

1. Add a misconfigured config (e.g. with missing "passwordProtectionSettings")
2. Try to use `Authenticator` normally
3. Unclear error is thrown
`MissingConfigurationException{message=Missing auth configuration, cause=null, recoverySuggestion=Make sure the Auth plugin is added and Amplify.configure is called. See https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/ for details}`

### Code Snippet

Nothing special, just do the basic setup of Authenticator, while having misconfigured json, like described [in documentation](https://ui.docs.amplify.aws/android/connected-components/authenticator)

**Comment by tylerjroach** [comment]
Thank you for the report. We will look to add better logging, error messaging for these types of scenarios.

**Comment by mattcreaser** [comment]
This improvement was released with Authenticator `1.1.0` 🎉
